### ISSUE TITLE
Support Creedmoor scale

### ISSUE THREAD

**Issue by erichiggins** [ammolytics/open-trickler-peripheral#2]
Often requested.
Seee #1

**Comment by cofagegaetaph** [comment]
The Creedmoor scale, also known as the Creedmoor system, is a method used for scoring in long-range target shooting, particularly in disciplines like fullbore rifle and Palma shooting. Developed in the late 19th century, the system for [Best budget scope for 6.5 Creedmoor](https://medium.com/@fadimahar02/best-scope-for-6-5-creedmoor-d280cf02dd02) was named after the Creedmoor Range in New York, where many early long-range competitions were held.
